version: '3.2'
services:
  moodle:
    image: x86dev/docker-ttrss:latest
    restart: always
    ports:
     - "8080:8080"
     - "8081:4443"
    volumes:
     - "/opt/docker/tinyrss/volumes/www:/var/www/"
    environment:
     - TTRSS_PORT=8080
 #    - DB_TYPE=mysql
 #    - DB_NAME=ttrssdb
 #    - DB_USER=ttrssus
 #    - DB_PASS=ttrsspw
  
    links:
    - mysql:db 

  mysql:
    image: mariadb:10.4.10-bionic
    container_name: mariadb
    restart: always
    ports:
    - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: cla2019ve
    volumes:
     - "/opt/docker/tinyrss/volumes/mariadb/:/var/lib/mysql"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:edge-4.9
    container_name: phpMyAdmin
    restart: always
    ports:
     - "8085:80"
     - "8086:443"
    environment:
     - "PMA_HOST=mysql"
     - "PMA_PORT=3306"
#     - "PMA_ABSOLUTE_URI=https://localhost"
    volumes:
     - "/opt/docker/tinyrss/volumes/phpmyadmin/sessions:/sessions"

